### ISSUE TITLE
missing return statement.

### ISSUE THREAD

**Issue by so4pmaker** [globocom/megadraft-related-articles-plugin#1]
I believe a return statement is missing in the render method in Readme's Usage section. 

```
class Example extends React.Component {
  render(){
    <Megadraft plugins={[plugin]} />
  }
}
```

**Comment by ricobl** [comment]
You're right @so4pmaker!

I'm fixing it! Thanks for pointing that out!

**Comment by ricobl** [comment]
Fixed on https://github.com/globocom/megadraft-related-articles-plugin/commits/master.
